image: node:20

pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build --configuration production --base-href /site-forms/
    - mv dist/we-forms-mag public
  artifacts:
    paths:
      - public
  only:
    - main
